version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${VAULTWARDEN_SECRET}
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: http
      traefik.http.routers.vaultwarden.rule: Host(`vault.${DOMAIN_NAME}`)
      traefik.http.middlewares.vaultwarden-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.vaultwarden.middlewares: vaultwarden-https-redirect
      traefik.http.routers.vaultwarden-secure.entrypoints: https
      traefik.http.routers.vaultwarden-secure.rule: Host(`vault.${DOMAIN_NAME}`)
      traefik.http.routers.vaultwarden-secure.tls: true
      traefik.http.routers.vaultwarden-secure.middlewares: default-headers@file
      traefik.http.routers.vaultwarden-secure.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.scheme: https
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.docker.network: proxy
    volumes:
      - ./vaultwarden/data:/data
    networks:
      - proxy

networks:
  proxy: 
    external: true
