version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: https://${GRAFANA_BASE_URL}
      GF_AUTH_GENERIC_OAUTH_ENABLED: true
      GF_AUTH_GENERIC_OAUTH_NAME: Authentik
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${GRAFANA_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GRAFANA_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://${AUTHENTIK_BASE_URL}/application/o/authorize/
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://${AUTHENTIK_BASE_URL}/application/o/token/
      GF_AUTH_GENERIC_OAUTH_API_URL: https://${AUTHENTIK_BASE_URL}/application/o/userinfo/
      GF_AUTH_SIGNOUT_REDIRECT_URL: https://${AUTHENTIK_BASE_URL}/application/o/grafana/end-session/
      GF_AUTH_OAUTH_AUTO_LOGIN: true
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'
      GF_INSTALL_PLUGINS: https://github.com/tribe29/grafana-checkmk-datasource/releases/download/v3.0.0-beta.1/tribe-29-checkmk-datasource-3.0.0-beta.1.zip;tribe-29-checkmk-datasource
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: tribe-29-checkmk-datasource
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: http
      traefik.http.routers.grafana.rule: Host(`grafana.${DOMAIN_NAME}`)
      traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.grafana.middlewares: grafana-https-redirect
      traefik.http.routers.grafana-secure.entrypoints: https
      traefik.http.routers.grafana-secure.rule: Host(`grafana.${DOMAIN_NAME}`)
      traefik.http.routers.grafana-secure.tls: true
      traefik.http.routers.grafana-secure.service: grafana
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      traefik.docker.network: proxy
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - proxy

networks:
  proxy: 
    external: true
